 export const vistas = {
  
   documentos_listado_productos_por_cierre : 'vw_documentos_listado_productos_por_cierre',
    acumulados_por_empleado : 'vw_empleados_acumulados_por_empleado',
   corte_de_caja : 'vw_corte_de_caja',
  corte_de_caja_parcial : 'vw_corte_de_caja_parcial',
  corte_de_caja_pagos : 'vw_corte_de_caja_pagos',
   documentos_clientes:'documentos_clientes',
    vehiculos_propietario : 'vw_vehiculos_propietario',
   empleados_tipo:'vw_empleados_tipo',
   empleados:'vw_empleados_obj',
   vehiculos_servicios_costos:'vw_vehiculos_servicios_costos',
  vehiculos_servicios:'vw_inv_mst_servicios',
   vehiculos_tipos :"vw_inv_mst_vehiculos_tipos",
  cajas : "vw_cajas" ,
  medios : "vw_medios" ,
  tiposDeDocumentos:'vw_tipos_de_documentos',
  prd_bodegas_inventario:'vw_inv_bodegas',
  mediosPorCajaActiva : "vw_medios_de_cajas_activas" ,
   categorias : "vw_inv_categorias" ,
   cajasActivas : "vw_cajas_activas" ,
   ventasCerradas : "vw_obj_ventas" ,

   ciudades : "vw_mst_per_clientes_ciudades" ,
    departamento: "vw_mst_per_clientes_deptos" ,

    maestros: "vw_maestros" ,
    tablasPorUsuario:'vw_tablas_usuarios',
    cajas_por_usuario :'vw_cajas_por_usuario',
    usuario : 'vw_usuario',
    establecimiento: 'vw_establecimiento',
    tipo_establecimiento: 'vw_tipo_establecimiento',
    documento: 'vw_obj_documentos',
    contadores:'vw_contadores',
    tipos_documentos_con_cont: 'vw_t_documentos_con_cont',
    domicilios:'vw_documentos_domicilio',
    vehiculos_servicios_tipos:'vw_inv_mst_tipos_servicios',
    productos:'vw_productos_con_existencia',
    marcas:'vw_inv_marcas' , 
    prd_inventario:'vw_prd_inventario',
    aux_ingreso_inventario : 'vw_inv_inventario_ingreso_auxiliar',
    vw_mst_per_clientes : 'vw_mst_per_clientes'
 }

