 export const vistas = {
  vw_inv_descuentos_actividad:'vw_inv_descuentos_actividad', 
  act_det_tmp_producto : 'vw_act_det_tmp_producto',
  act_det_tmp_cliente : 'vw_act_det_tmp_cliente',
  act_det_tmp_categoria : 'vw_act_det_tmp_categoria',
  act_det_tmp_marca : 'vw_act_det_tmp_marca', 
  act_det_producto : 'vw_act_det_producto',
  act_det_cliente : 'vw_act_det_cliente',
  act_det_categoria : 'vw_act_det_categoria',
  act_det_marca : 'vw_act_det_marca',


  vw_actividad_disponible_categoria:'vw_actividad_disponible_categoria',
  vw_actividad_disponible_cliente:'vw_actividad_disponible_cliente',
  vw_actividad_disponible_producto:'vw_actividad_disponible_producto',
  vw_actividad_disponible_marca:'vw_actividad_disponible_marca',
  vw_operaciones_obj:'vw_operaciones_obj',
   documentos_listado_productos_por_cierre : 'vw_documentos_listado_productos_por_cierre',
    acumulados_por_empleado : 'vw_empleados_acumulados_por_empleado',
   corte_de_caja : 'vw_corte_de_caja',
  corte_de_caja_parcial : 'vw_corte_de_caja_parcial',
  corte_de_caja_pagos : 'vw_corte_de_caja_pagos',
   documentos_clientes:'documentos_clientes',
    vehiculos_propietario : 'vw_vehiculos_propietario',
   empleados_tipo:'vw_empleados_tipo',
   empleados:'vw_empleados_obj',
   vehiculos_servicios_costos:'vw_vehiculos_servicios_costos',
  vehiculos_servicios:'vw_inv_mst_servicios',
   vehiculos_tipos :"vw_inv_mst_vehiculos_tipos",
  cajas : "vw_cajas" ,
  medios : "vw_medios" ,
  tiposDeDocumentos:'vw_tipos_de_documentos',
  prd_bodegas_inventario:'vw_inv_bodegas',
  mediosPorCajaActiva : "vw_medios_de_cajas_activas" ,
  categorias : "vw_inv_categorias" ,
  categoriasVendidas : "vw_inv_categorias_vendidos" ,
   cajasActivas : "vw_cajas_activas" ,
   documentos_por_tip_documento : "vw_obj_documentos_por_tipo_documento_final" ,
   vw_obj_documentos_por_usuario:"vw_obj_documentos_por_usuario",
   vw_obj_documentos_por_cliente:"vw_obj_documentos_por_cliente",
   ventasCerradas : "vw_obj_ventas" ,
   ventasACreditoCerradas : "vw_obj_ventas_credito" ,
   inv_descuentos : "vw_inv_descuentos" ,

   ciudades : "vw_mst_per_clientes_ciudades" ,
    departamento: "vw_mst_per_clientes_deptos" ,
    vw_productos_vendidos:'vw_productos_vendidos',
    maestros: "vw_maestros" ,
    tablasPorUsuario:'vw_tablas_usuarios',
    cajas_por_usuario :'vw_cajas_por_usuario',
    usuario : 'vw_usuario',
    usuarioConVentas : 'vw_usuario_con_ventas',
    establecimiento: 'vw_establecimiento',
    tipo_establecimiento: 'vw_tipo_establecimiento',
    documento: 'vw_obj_documentos',
    documentoDev: 'vw_obj_documentos_devolucion',
    documentosCompra: 'vw_obj_documentos_compra',
    documentosPagosCPP: 'vw_obj_documentos_pagos_CPP',
    documentosCuentasPorPagar: 'vw_obj_documentos_cuentas_por_pagar',
    cartera: 'vw_mst_mov_cartera',
    credito: 'vw_mst_mov_credito',
    carteraAbonos: 'vw_mst_mov_cartera_abonos',
    contadores:'vw_contadores',
    tipos_documentos_con_cont: 'vw_t_documentos_con_cont',
    domicilios:'vw_documentos_domicilio',
    vehiculos_servicios_tipos:'vw_inv_mst_tipos_servicios',
    productos:'vw_productos_obj',
    productos_con_existencia:'vw_productos_con_existencia',
    marcas:'vw_inv_marcas' , 
    prd_inventario:'vw_prd_inventario',
    inv_mst_producto:'vw_inv_mst_producto',
    aux_ingreso_inventario : 'vw_inv_inventario_ingreso_auxiliar',
    vw_mst_per_clientes : 'vw_mst_per_clientes' ,
    vw_proveedor : 'vw_mst_per_proveedores' ,

    vw_cnt_clase: 'vw_cnt_clase',
vw_cnt_grupos: 'vw_cnt_grupos',
vw_cnt_scuentas: 'vw_cnt_scuentas',
vw_cnt_cajas_asignadas: 'vw_cuentas_Cajas_Asignadas',
vw_cnt_con_movimientos: 'vw_cuentas_con_movimientos',
vw_cnt_gasto_asignadas: 'vw_cuentas_Gasto_Asignadas',
vw_cnt_operaciones:'vw_cnt_operaciones',
vw_cnt_oper_auto:'vw_cnt_operaciones_automaticas',
vw_cnt_oper_manuales:'vw_cnt_operaciones_manuales',
vw_cnt_cuenta_mayores: 'vw_cnt_cuenta',
vw_transacciones: 'vw_transacciones',
vw_transacciones_tmp: 'vw_transacciones_tmp',
vendedores: 'vw_mst_per_empleados_vendedores',
vendedoresConVentas: 'vw_mst_per_empleados_vendedores_con_ventas',

operaPrestablecidas:'cnt_operacion_prestablecidas',

operaPrestablecidasCuentas:'vw_cnt_operacion_prestablecidas_cuentas',

operaPrestablecidasCuentasConSaldo:'vw_cnt_operacion_prestablecidas_cuentas_con_saldo'


 }

